### ISSUE TITLE
Przerobienie pluginu pod werjsę 1.13.2 i  w górę.

### ISSUE THREAD

**Issue by whoyoux** [grzegorz2047/PayInItemsForGuild#1]

**Comment by grzegorz2047** [comment]
Kwestia podpięcia się pod nowe api.

**Comment by grzegorz2047** [comment]
Dodane do zakładki https://github.com/grzegorz2047/PayInItemsForGuild/releases jako v1.1
Wygeneruj na nowo config.yml
Powodzenia!
